[project]
name = "letsrolld"
version = "0.1.0"
description = "Letsrolld, movie recommendation engine"
authors = [
    {name = "Ihar Hrachyshka", email = "ihar.hrachyshka@gmail.com"},
]
dependencies = [
    "beautifulsoup4",
    # TODO: remove this dependency
    "cli-color-py",
    "requests",
    # TODO: vendorize this dependency, or otherwise replace it
    "simple-justwatch-python-api",
    "SQLAlchemy>=2.0.27",
    "alembic>=1.13.1",
]
requires-python = ">=3.11,<3.12"
readme = "README.md"
license = {text = "GPL-3.0-only"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.black]
line-length = 79

[tool.pdm.dev-dependencies]
dev = [
    "pre-commit>=3.6.2",
    "pytest>=8.0.1",
]

[project.scripts]
# TODO: remove these obsolete scripts
recommend = "letsrolld.cmd.recommend:main"
directors = "letsrolld.cmd.directors:main"

db-init = "letsrolld.cmd.db_init:main"
populate-directors = "letsrolld.cmd.populate_directors:main"
# TODO: rename to just `update`
update-directors = "letsrolld.cmd.update_directors:directors_main"
update-films = "letsrolld.cmd.update_directors:films_main"
update-offers = "letsrolld.cmd.update_directors:offers_main"
cleanup = "letsrolld.cmd.cleanup:main"

# webapi
webapp = "letsrolld.webapi.app:main"
