#
# This is a flox environment manifest.
# Visit flox.dev/docs/concepts/manifest/
# or see flox-edit(1) for more information
#

# List packages you wish to install in your environment inside
# the 'install' section

[install]
pdm.pkg-path = "pdm"
python311.pkg-path = "python311"
sqlalchemy.pkg-path = "python311Packages.sqlalchemy"
pre-commit.pkg-path = "pre-commit"
pytest.pkg-path = "python311Packages.pytest"
beautifulsoup4.pkg-path = "python311Packages.beautifulsoup4"
requests.pkg-path = "python311Packages.requests"
alembic.pkg-path = "python311Packages.alembic"
sqlite.pkg-path = "sqlite"
gnumake.pkg-path = "gnumake"
flask.pkg-path = "python311Packages.flask"
flask-restful.pkg-path = "python311Packages.flask-restful"
flask-sqlalchemy.pkg-path = "python311Packages.flask-sqlalchemy"
flask-cors.pkg-path = "python311Packages.flask-cors"
http-server.pkg-path = "nodePackages.http-server"
moreutils.pkg-path = "moreutils"
openapi-generator-cli.pkg-path = "openapi-generator-cli"
pycountry.pkg-path = "python311Packages.pycountry"
act.pkg-path = "act"
pip.pkg-path = "python311Packages.pip"
shellcheck.pkg-path = "shellcheck"
# hello.pkg-path = "hello"
# nodejs = { version = "^18.4.2", pkg-path = "nodejs_18" }

# Set an environment variable.
# These variables may not reference once another
# and are added to the environment without expansion.

[vars]
# message = "Howdy"
# pass-in = "$some-env-var"

# An activation hook will be run when entering the environment.
# You can define one in the 'hook' table inline via the 'script' field,
# or provide a file using the 'file' field.
# If 'file' is provided, the path should be relative to this file.
# If both 'file' and 'script' are provided,
# only the hook defined in 'file' will be run .

[hook]
# script = """
#   echo "it's gettin flox in here";
# """

# An environment that works on one system is guaranteed to work on the
# same type of system,
# but other systems may not have the same packages available, etc.
# In order to use the environment on a system you must explicitly
# add it to this list.
[options]
systems = ["x86_64-darwin", "aarch64-darwin"]
